import "@v1/ui/globals.css";
import { cn } from "@v1/ui/cn";
import { Providers } from "@/components/providers/providers";
import { ReactScan } from "@/components/dev/react-scan";
import type { Metadata } from "next";
import { GeistMono } from "geist/font/mono";
import { GeistSans } from "geist/font/sans";
import localFont from "next/font/local";

// ABC Diatype Font Family
const abcDiatype = localFont({
  src: [
    {
      path: "../../fonts/ABCDiatype-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../fonts/ABCDiatype-Medium.woff2", 
      weight: "500",
      style: "normal",
    },
    {
      path: "../../fonts/ABCDiatype-Bold.woff2",
      weight: "700", 
      style: "normal",
    },
  ],
  variable: "--font-abc-diatype",
  display: "swap",
});

// ABC Diatype Mono Font Family  
const abcDiatypeMono = localFont({
  src: [
    {
      path: "../../fonts/ABCDiatypeMono-Regular.woff2",
      weight: "400",
      style: "normal", 
    },
    {
      path: "../../fonts/ABCDiatypeMono-RegularItalic.woff2",
      weight: "400",
      style: "italic",
    },
  ],
  variable: "--font-abc-diatype-mono",
  display: "swap", 
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export const viewport = {
  themeColor: [
    { media: "(prefers-color-scheme: light)" },
    { media: "(prefers-color-scheme: dark)" },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <head />
      <body
        className={cn(
          `${GeistSans.variable} ${GeistMono.variable} ${abcDiatype.variable} ${abcDiatypeMono.variable}`,
          "antialiased",
        )}
      >
        <Providers>
          <ReactScan />
          {children}
        </Providers>
      </body>
    </html>
  );
}
