// Icon/emoji picker options for watchlist groups.
// Kept out of watchlist-group-icon.tsx so that file only exports components (Fast Refresh).

export const AVAILABLE_ICONS = {
  emojis: [
    { key: '💩', label: 'Poop', emoji: '💩' },
    { key: '🚀', label: 'Rocket', emoji: '🚀' },
    { key: '💎', label: 'Diamond', emoji: '💎' },
    { key: '🔥', label: 'Fire', emoji: '🔥' },
    { key: '⭐', label: 'Star', emoji: '⭐' },
    { key: '👑', label: 'Crown', emoji: '👑' },
    { key: '🎯', label: 'Target', emoji: '🎯' },
    { key: '💰', label: 'Money bag', emoji: '💰' },
    { key: '🌙', label: 'Moon', emoji: '🌙' },
    { key: '⚡', label: 'Lightning', emoji: '⚡' },
    { key: '🦄', label: 'Unicorn', emoji: '🦄' },
    { key: '🐻', label: 'Bear', emoji: '🐻' },
    { key: '🐂', label: 'Bull', emoji: '🐂' },
    { key: '💀', label: 'Skull', emoji: '💀' },
    { key: '🎪', label: 'Circus', emoji: '🎪' },
    { key: '🌈', label: 'Rainbow', emoji: '🌈' },
    { key: '🔮', label: 'Crystal ball', emoji: '🔮' },
    { key: '🎭', label: 'Theater', emoji: '🎭' },
    { key: '🎲', label: 'Dice', emoji: '🎲' },
    { key: '🎨', label: 'Art', emoji: '🎨' },
    { key: '📈', label: 'Chart up', emoji: '📈' },
    { key: '📉', label: 'Chart down', emoji: '📉' },
    { key: '💹', label: 'Markets', emoji: '💹' },
    { key: '📊', label: 'Bar chart', emoji: '📊' },
    { key: '🏦', label: 'Bank', emoji: '🏦' },
    { key: '🧠', label: 'Brain', emoji: '🧠' },
    { key: '🏆', label: 'Trophy', emoji: '🏆' },
    { key: '🎁', label: 'Gift', emoji: '🎁' },
    { key: '🐋', label: 'Whale', emoji: '🐋' },
    { key: '🦅', label: 'Eagle', emoji: '🦅' },
    { key: '🌊', label: 'Wave', emoji: '🌊' },
    { key: '☀️', label: 'Sun', emoji: '☀️' },
    { key: '🍀', label: 'Clover', emoji: '🍀' },
    { key: '✨', label: 'Sparkles', emoji: '✨' },
    { key: '🤖', label: 'Robot', emoji: '🤖' },
    { key: '🪙', label: 'Coin', emoji: '🪙' },
    { key: '⚙️', label: 'Gear', emoji: '⚙️' },
    { key: '🛡️', label: 'Shield', emoji: '🛡️' },
    { key: '🌍', label: 'Globe', emoji: '🌍' },
    { key: '👀', label: 'Eyes', emoji: '👀' },
    { key: '🧪', label: 'Science', emoji: '🧪' },
    { key: '🏠', label: 'Home', emoji: '🏠' },
    { key: '🎵', label: 'Music', emoji: '🎵' },
    { key: '🍕', label: 'Pizza', emoji: '🍕' },
    { key: '⚽', label: 'Soccer', emoji: '⚽' },
    { key: '🎮', label: 'Video game', emoji: '🎮' },
    { key: '💼', label: 'Briefcase', emoji: '💼' },
    { key: '🧊', label: 'Ice', emoji: '🧊' },
  ],
  icons: [
    { key: 'sparkles', label: 'Sparkles' },
    { key: 'graduation-cap', label: 'Graduation cap' },
    { key: 'star', label: 'Star' },
    { key: 'fire', label: 'Flame' },
    { key: 'lightning', label: 'Lightning' },
    { key: 'diamond', label: 'Diamond' },
    { key: 'crown', label: 'Crown' },
    { key: 'target', label: 'Target' },
    { key: 'moon', label: 'Moon' },
    { key: 'chart', label: 'Chart up' },
    { key: 'chart-down', label: 'Chart down' },
    { key: 'bars', label: 'Bars' },
    { key: 'eye', label: 'Eye' },
    { key: 'time', label: 'Time' },
    { key: 'bell', label: 'Bell' },
    { key: 'heart', label: 'Heart' },
    { key: 'bookmark', label: 'Bookmark' },
    { key: 'seal', label: 'Seal' },
    { key: 'dots', label: 'Dots' },
    { key: 'banknote', label: 'Banknote' },
    { key: 'bitcoin', label: 'Bitcoin' },
    { key: 'wallet', label: 'Wallet' },
    { key: 'globe', label: 'Globe' },
    { key: 'shield', label: 'Shield' },
    { key: 'trophy', label: 'Trophy' },
    { key: 'gift', label: 'Gift' },
    { key: 'infinity', label: 'Infinity' },
    { key: 'rainbow', label: 'Rainbow' },
    { key: 'house', label: 'House' },
    { key: 'flag', label: 'Flag' },
    { key: 'party', label: 'Party' },
    { key: 'balloon', label: 'Balloon' },
    { key: 'leaf', label: 'Leaf' },
    { key: 'tree', label: 'Tree' },
    { key: 'pawprint', label: 'Paw' },
    { key: 'fish', label: 'Fish' },
    { key: 'cat', label: 'Cat' },
    { key: 'dog', label: 'Dog' },
    { key: 'camera', label: 'Camera' },
    { key: 'game', label: 'Game' },
    { key: 'american-football', label: 'Football' },
    { key: 'volleyball', label: 'Volleyball' },
    { key: 'sketch', label: 'Sketch' },
  ],
}
