project_id = "create-v1"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "auth"]
extra_search_path = ["public", "auth"]
max_rows = 100

[auth]
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000", "http://localhost:54321/auth/v1/callback"]
jwt_expiry = 36000

[db]
port = 54322

[studio]
port = 54323

[auth.external.google]
enabled = true
client_id = "151257648416-81e5tbg7j8llhvtv9asa3b36fnqo50vf.apps.googleusercontent.com"
secret = "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"
redirect_uri = "http://localhost:54321/auth/v1/callback"

[auth.email]
double_confirm_changes = true
enable_confirmations = true
enable_signup = true

[analytics]
enabled = false
port = 54327
vector_port = 54328
backend = "postgres"